# build and deploy release branch to GH pages

name: Build and Deploy Release branch to GH pages

# after the next release this should be updated to true
env:
  CI: true

on:
  push:
    branches: ["release"]
  pull_request:
    types: closed
    branches: ["release"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "release"
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run build:HarmonyExport
      # - run: npm test
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
