# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  CI: false
  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: "wget https://harmonydata.github.io/website/public.tar.gz"
      name: Download static page. The source is in https://github.com/harmonydata/website. 
    - run: "tar -xvf public.tar.gz -C ./public"
      name: Unzip the tar
    - run: "mv public/public public/blog"
      name: Place the static blog content under public/blog
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
